/*
 *
 * @author Zam
 */

package assignment1;

// necassary imports. 

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.System.exit;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;



public class Assignment1Frame extends javax.swing.JFrame {

    
    /**
     * Creating Frame
     */
    public Assignment1Frame() {
        
        
        initComponents();
        
        xTurn = false;
        x2Turn = false;
        cross = new JButton[8][8];
        
        cross[0][0] = jButton1;
        cross[0][1] = jButton2;
        cross[0][2] = jButton3;
        cross[0][3] = jButton4;
        cross[0][4] = jButton5;
        cross[0][5] = jButton6;
        cross[0][6] = jButton7;
        cross[0][7] = jButton8;
        
        cross[1][0] = jButton9;
        cross[1][1] = jButton10;
        cross[1][2] = jButton11;
        cross[1][3] = jButton12;
        cross[1][4] = jButton13;
        cross[1][5] = jButton14;
        cross[1][6] = jButton15;
        cross[1][7] = jButton16;
        
        cross[2][0] = jButton17;
        cross[2][1] = jButton18;
        cross[2][2] = jButton19;
        cross[2][3] = jButton20;
        cross[2][4] = jButton21;
        cross[2][5] = jButton22;
        cross[2][6] = jButton23;
        cross[2][7] = jButton24;
        
        cross[3][0] = jButton25;
        cross[3][1] = jButton26;
        cross[3][2] = jButton27;
        cross[3][3] = jButton28;
        cross[3][4] = jButton29;
        cross[3][5] = jButton30;
        cross[3][6] = jButton31;
        cross[3][7] = jButton32;
       
        cross[4][0] = jButton33;
        cross[4][1] = jButton34;
        cross[4][2] = jButton35;
        cross[4][3] = jButton36;
        cross[4][4] = jButton37;
        cross[4][5] = jButton38;
        cross[4][6] = jButton39;
        cross[4][7] = jButton40;
        
        cross[5][0] = jButton41;
        cross[5][1] = jButton42;
        cross[5][2] = jButton43;
        cross[5][3] = jButton44;
        cross[5][4] = jButton45;
        cross[5][5] = jButton46;
        cross[5][6] = jButton47;
        cross[5][7] = jButton48;
        
        cross[6][0] = jButton49;
        cross[6][1] = jButton50;
        cross[6][2] = jButton51;
        cross[6][3] = jButton52;
        cross[6][4] = jButton53;
        cross[6][5] = jButton54;
        cross[6][6] = jButton55;
        cross[6][7] = jButton56;

        cross[7][0] = jButton57;
        cross[7][1] = jButton58;
        cross[7][2] = jButton59;
        cross[7][3] = jButton60;
        cross[7][4] = jButton61;
        cross[7][5] = jButton62;
        cross[7][6] = jButton63;
        cross[7][7] = jButton64;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton65 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zam_2019");

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Player One");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Player Two");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Player Three");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(jLabel3, gridBagConstraints);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(jTextField1, gridBagConstraints);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(jTextField2, gridBagConstraints);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(jTextField3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridLayout(8, 8, 1, 1));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);

        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);

        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12);

        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);

        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14);

        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15);

        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16);

        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17);

        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton18);

        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton19);

        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton20);

        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton21);

        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton22);

        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton23);

        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton24);

        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton25);

        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton26);

        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton27);

        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton28);

        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton29);

        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton30);

        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton31);

        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton32);

        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton33);

        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton34);

        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton35);

        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton36);

        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton37);

        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton38);

        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton39);

        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton40);

        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton41);

        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton42);

        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton43);

        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton44);

        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton45);

        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton46);

        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton47);

        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton48);

        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton49);

        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton50);

        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton51);

        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton52);

        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton53);

        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton54);

        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton55);

        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton56);

        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton57);

        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton58);

        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton59);

        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton60);

        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton61);

        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton62);

        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton63);

        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton64);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        jButton65.setBackground(new java.awt.Color(204, 255, 204));
        jButton65.setText("RESET (NEW GAME)");
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton65);
        jButton65.getAccessibleContext().setAccessibleDescription("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        jPanel1.add(jPanel4, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        JButton button = (JButton) evt.getSource();
        selectButton(button);
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        
        //This is restar buttion
        //reserts all the buttons text value
        
        //clearing default text from buttons.
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");

        jButton9.setText("");
        jButton10.setText("");
        jButton11.setText("");
        jButton12.setText("");
        jButton13.setText("");
        jButton14.setText("");
        jButton15.setText("");
        jButton16.setText("");

        jButton17.setText("");
        jButton18.setText("");
        jButton19.setText("");
        jButton20.setText("");
        jButton21.setText("");
        jButton22.setText("");
        jButton23.setText("");
        jButton24.setText("");

        jButton25.setText("");
        jButton26.setText("");
        jButton27.setText("");
        jButton28.setText("");
        jButton29.setText("");
        jButton30.setText("");
        jButton31.setText("");
        jButton32.setText("");

        jButton33.setText("");
        jButton34.setText("");
        jButton35.setText("");
        jButton36.setText("");
        jButton37.setText("");
        jButton38.setText("");
        jButton39.setText("");
        jButton40.setText("");

        jButton41.setText("");
        jButton42.setText("");
        jButton43.setText("");
        jButton44.setText("");
        jButton45.setText("");
        jButton46.setText("");
        jButton47.setText("");
        jButton48.setText("");

        jButton49.setText("");
        jButton50.setText("");
        jButton51.setText("");
        jButton52.setText("");
        jButton53.setText("");
        jButton54.setText("");
        jButton55.setText("");
        jButton56.setText("");

        jButton57.setText("");
        jButton58.setText("");
        jButton59.setText("");
        jButton60.setText("");
        jButton61.setText("");
        jButton62.setText("");
        jButton63.setText("");
        jButton64.setText("");

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        xTurn = false;
        x2Turn = false;
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

     /* 
         the fields of this object 'userInput' are not reachable thru here;
         I have tried all the possible options, but not reachable.
         I wanted to to use Players names, thier symbols to mark buttons.
         Since I could not reach the symbols, so I am marking 'X' for Player one
         'Y' for Player Two and 'Z' for Player-3.
         To be more specific, this instance of class and fields are only available within main()
         NOT available to other methods.
        */

    
    
    
    public void selectButton(JButton button) {
        String playerOne = jTextField1.getText();
        String playerTwo = jTextField2.getText();
        String playerThree = jTextField3.getText();
        if ((!playerOne.equals(playerTwo)) || (!playerOne.equals(playerThree)) || !playerTwo.equals(playerThree)){
            if (button.getText().equals("")) {
                if (xTurn == false && x2Turn == false) {
                    button.setText(playerOne);
                    xTurn = false;
                    x2Turn = true;
                } else if (xTurn == false && x2Turn == true) {
                    button.setText(playerTwo);
                    xTurn = true;
                    x2Turn = false;
                } else {
                    button.setText(playerThree);
                    xTurn = false;
                    x2Turn = false;
                        }
            }
            checkForTheWin();
        } else {
            JOptionPane.showMessageDialog(this, "Player symbols are automatically assigned"
                    + " if the user chooses the same characters. Change the characters or proceed"
                    + " with the computer assigned characters.");          
            jTextField1.setText("x");
            jTextField2.setText("y");
            jTextField3.setText("z");
            
        }
    }
    
    
    //method to check who wins the game.
    void checkForTheWin() {
        getRCD();
    }
    
    public String inputProcessor(String input) {
        //input string to carry text message 
        if (input.equals("")){
            String output = "`";
            return output;
        } else {
            return input;
        }
        }
    
    public void winCondition(String input) {
        //winning logic- method
        String x = jTextField1.getText();
        String y = jTextField2.getText();
        String z = jTextField3.getText();
        if (input.contains(x+x+x+x)){
            JOptionPane.showMessageDialog(this, "The winner is: " + jLabel1.getText());          
        } else if (input.contains(y+y+y+y)) {
            JOptionPane.showMessageDialog(this, "The winner is: " + jLabel2.getText());
        } else if (input.contains(z+z+z+z)) {
            JOptionPane.showMessageDialog(this, "The winner is: " + jLabel3.getText());
        }
        
    }
    
    public void getRCD() {
        //identifying rows, columns, and diagonal occurances.

        
//i need to learn smarter way to navigate array of arrays. 
        String row1col1 = jButton1.getText();
        row1col1 = inputProcessor(row1col1);
        String row1col2 = jButton2.getText();
        row1col2 = inputProcessor(row1col2);
        String row1col3 = jButton3.getText();
        row1col3 = inputProcessor(row1col3);
        String row1col4 = jButton4.getText();
        row1col4 = inputProcessor(row1col4);
        String row1col5 = jButton5.getText();
        row1col5 = inputProcessor(row1col5);
        String row1col6 = jButton6.getText();
        row1col6 = inputProcessor(row1col6);
        String row1col7 = jButton7.getText();
        row1col7 = inputProcessor(row1col7);
        String row1col8 = jButton8.getText();
        row1col8 = inputProcessor(row1col8);

        String row1Total = (row1col1 + row1col2 + row1col3 + row1col4 +
                row1col5 +row1col6 + row1col7 + row1col8);
        System.out.println("Row1:" + row1Total);
        winCondition(row1Total);
         
        String row2col1 = jButton9.getText();
        row2col1 = inputProcessor(row2col1);
        String row2col2 = jButton10.getText();
        row2col2 = inputProcessor(row2col2);
        String row2col3 = jButton11.getText();
        row2col3 = inputProcessor(row2col3);
        String row2col4 = jButton12.getText();
        row2col4 = inputProcessor(row2col4);
        String row2col5 = jButton13.getText();
        row2col5 = inputProcessor(row2col5);
        String row2col6 = jButton14.getText();
        row2col6 = inputProcessor(row2col6);
        String row2col7 = jButton15.getText();
        row2col7 = inputProcessor(row2col7);
        String row2col8 = jButton16.getText();
        row2col8 = inputProcessor(row2col8);

        String row2Total = (row2col1 + row2col2 + row2col3 + row2col4 +
                row2col5 +row2col6 + row2col7 + row2col8);
        System.out.println("Row2:" + row2Total);
        winCondition(row2Total);
        
        String row3col1 = jButton17.getText();
        row3col1 = inputProcessor(row3col1);
        String row3col2 = jButton18.getText();
        row3col2 = inputProcessor(row3col2);
        String row3col3 = jButton19.getText();
        row3col3 = inputProcessor(row3col3);
        String row3col4 = jButton20.getText();
        row3col4 = inputProcessor(row3col4);
        String row3col5 = jButton21.getText();
        row3col5 = inputProcessor(row3col5);
        String row3col6 = jButton22.getText();
        row3col6 = inputProcessor(row3col6);
        String row3col7 = jButton23.getText();
        row3col7 = inputProcessor(row3col7);
        String row3col8 = jButton24.getText();
        row3col8 = inputProcessor(row3col8);

        String row3Total = (row3col1 + row3col2 + row3col3 + row3col4 +
                row3col5 +row3col6 + row3col7 + row3col8);
        System.out.println("Row3:" + row3Total);
        winCondition(row3Total);

        String row4col1 = jButton25.getText();
        row4col1 = inputProcessor(row4col1);
        String row4col2 = jButton26.getText();
        row4col2 = inputProcessor(row4col2);
        String row4col3 = jButton27.getText();
        row4col3 = inputProcessor(row4col3);
        String row4col4 = jButton28.getText();
        row4col4 = inputProcessor(row4col4);
        String row4col5 = jButton29.getText();
        row4col5 = inputProcessor(row4col5);
        String row4col6 = jButton30.getText();
        row4col6 = inputProcessor(row4col6);
        String row4col7 = jButton31.getText();
        row4col7 = inputProcessor(row4col7);
        String row4col8 = jButton32.getText();
        row4col8 = inputProcessor(row4col8);

        String row4Total = (row4col1 + row4col2 + row4col3 + row4col4 +
                row4col5 +row4col6 + row4col7 + row4col8);
        System.out.println("Row4:" + row4Total);
        winCondition(row4Total);
        
        String row5col1 = jButton33.getText();
        row5col1 = inputProcessor(row5col1);
        String row5col2 = jButton34.getText();
        row5col2 = inputProcessor(row5col2);
        String row5col3 = jButton35.getText();
        row5col3 = inputProcessor(row5col3);
        String row5col4 = jButton36.getText();
        row5col4 = inputProcessor(row5col4);
        String row5col5 = jButton37.getText();
        row5col5 = inputProcessor(row5col5);
        String row5col6 = jButton38.getText();
        row5col6 = inputProcessor(row5col6);
        String row5col7 = jButton39.getText();
        row5col7 = inputProcessor(row5col7);
        String row5col8 = jButton40.getText();
        row5col8 = inputProcessor(row5col8);

        String row5Total = (row5col1 + row5col2 + row5col3 + row5col4 +
                row5col5 +row5col6 + row5col7 + row5col8);
        System.out.println("Row5:" + row5Total);
        winCondition(row5Total);

        String row6col1 = jButton41.getText();
        row6col1 = inputProcessor(row6col1);
        String row6col2 = jButton42.getText();
        row6col2 = inputProcessor(row6col2);
        String row6col3 = jButton43.getText();
        row6col3 = inputProcessor(row6col3);
        String row6col4 = jButton44.getText();
        row6col4 = inputProcessor(row6col4);
        String row6col5 = jButton45.getText();
        row6col5 = inputProcessor(row6col5);
        String row6col6 = jButton46.getText();
        row6col6 = inputProcessor(row6col6);
        String row6col7 = jButton47.getText();
        row6col7 = inputProcessor(row6col7);
        String row6col8 = jButton48.getText();
        row6col8 = inputProcessor(row6col8);

        String row6Total = (row6col1 + row6col2 + row6col3 + row6col4 +
                row6col5 +row6col6 + row6col7 + row6col8);
        System.out.println("Row6:" + row6Total);
        winCondition(row6Total);
        
        String row7col1 = jButton49.getText();
        row7col1 = inputProcessor(row7col1);
        String row7col2 = jButton50.getText();
        row7col2 = inputProcessor(row7col2);
        String row7col3 = jButton51.getText();
        row7col3 = inputProcessor(row7col3);
        String row7col4 = jButton52.getText();
        row7col4 = inputProcessor(row7col4);
        String row7col5 = jButton53.getText();
        row7col5 = inputProcessor(row7col5);
        String row7col6 = jButton54.getText();
        row7col6 = inputProcessor(row7col6);
        String row7col7 = jButton55.getText();
        row7col7 = inputProcessor(row7col7);
        String row7col8 = jButton56.getText();
        row7col8 = inputProcessor(row7col8);

        String row7Total = (row7col1 + row7col2 + row7col3 + row7col4 +
                row7col5 +row7col6 + row7col7 + row7col8);
        System.out.println("Row7:" + row7Total);
        winCondition(row7Total);

        String row8col1 = jButton57.getText();
        row8col1 = inputProcessor(row8col1);
        String row8col2 = jButton58.getText();
        row8col2 = inputProcessor(row8col2);
        String row8col3 = jButton59.getText();
        row8col3 = inputProcessor(row8col3);
        String row8col4 = jButton60.getText();
        row8col4 = inputProcessor(row8col4);
        String row8col5 = jButton61.getText();
        row8col5 = inputProcessor(row8col5);
        String row8col6 = jButton62.getText();
        row8col6 = inputProcessor(row8col6);
        String row8col7 = jButton63.getText();
        row8col7 = inputProcessor(row8col7);
        String row8col8 = jButton64.getText();
        row8col8 = inputProcessor(row8col8);

        String row8Total = (row8col1 + row8col2 + row8col3 + row8col4 +
                row8col5 +row8col6 + row8col7 + row8col8);
        System.out.println("Row8:" + row8Total);
        winCondition(row8Total);

//ROW CHECK

        String col1Total = (row1col1 + row2col1 + row3col1 + row4col1 +
                row5col1 +row6col1 + row7col1 + row8col1);
        System.out.println("Col1:" + col1Total);
        winCondition(col1Total);

        String col2Total = (row1col2 + row2col2 + row3col2 + row4col2 +
                row5col2 +row6col2 + row7col2 + row8col2);
        System.out.println("Col2:" + col2Total);
        winCondition(col2Total);

        String col3Total = (row1col3 + row2col3 + row3col3 + row4col3 +
                row5col3 +row6col3 + row7col3 + row8col3);
        System.out.println("Col3:" + col3Total);
        winCondition(col3Total);
        
        String col4Total = (row1col4 + row2col4 + row3col4 + row4col4 +
                row5col4 +row6col4 + row7col4 + row8col4);
        System.out.println("Col4:" + col4Total);
        winCondition(col4Total);
        
        String col5Total = (row1col5 + row2col5 + row3col5 + row4col5 +
                row5col5 +row6col5 + row7col5 + row8col5);
        System.out.println("Col5:" + col5Total);
        winCondition(col5Total);

        String col6Total = (row1col6 + row2col6 + row3col6 + row4col6 +
                row5col6 +row6col6 + row7col6 + row8col6);
        System.out.println("Col6:" + col6Total);
        winCondition(col6Total);

        String col7Total = (row1col7 + row2col7 + row3col7 + row4col7 +
                row5col7 +row6col7 + row7col7 + row8col7);
        System.out.println("Col7:" + col7Total);
        winCondition(col7Total);
        
        String col8Total = (row1col8 + row2col8 + row3col8 + row4col8 +
                row5col8 +row6col8 + row7col8 + row8col8);
        System.out.println("Col8:" + col8Total);
        winCondition(col8Total);

//Diagonal Check - top left to bottom right
        String leftDiagTotal1 = (row5col1 + row6col2 + row7col3 + row8col4);
        System.out.println("leftDiagTotal1" + leftDiagTotal1);
        winCondition(leftDiagTotal1);
        
        String leftDiagTotal2 = (row4col1 + row5col2 + row6col3 + row7col4 + row8col5);
        System.out.println("leftDiagTotal2" + leftDiagTotal2);
        winCondition(leftDiagTotal2);
        
        String leftDiagTotal3 = (row3col1 + row4col2 + row5col3 + row6col4 + row7col5 + row8col6);
        System.out.println("leftDiagTotal3" + leftDiagTotal3);
        winCondition(leftDiagTotal3);
        
        String leftDiagTotal4 = (row2col1 + row3col2 + row4col3 + row5col4 + row6col5 + row7col6 + row8col7);
        System.out.println("leftDiagTotal4" + leftDiagTotal4);
        winCondition(leftDiagTotal4);
        
        String leftDiagTotal5 = (row1col1 + row2col2 + row3col3 + row4col4 + row5col5 + row6col6 + row7col7 + row8col8);
        System.out.println("leftDiagTotal5" + leftDiagTotal5);
        winCondition(leftDiagTotal5);

        String leftDiagTotal6 = (row1col2 + row2col3 + row3col4 + row4col5 + row5col6 + row6col7 + row7col8);
        System.out.println("leftDiagTotal6" + leftDiagTotal6);
        winCondition(leftDiagTotal6);

        String leftDiagTotal7 = (row1col3 + row2col4 + row3col5 + row4col6 + row5col7 + row6col8);
        System.out.println("leftDiagTotal7" + leftDiagTotal7);
        winCondition(leftDiagTotal7);

        String leftDiagTotal8 = (row1col4 + row2col5 + row3col6 + row4col7 + row5col8);
        System.out.println("leftDiagTotal8" + leftDiagTotal8);
        winCondition(leftDiagTotal8);
        
        String leftDiagTotal9 = (row1col5 + row2col6 + row3col7 + row4col8);
        System.out.println("leftDiagTotal9" + leftDiagTotal9);
        winCondition(leftDiagTotal9);

//Diagonal Check - top right to bottom left
        String rightDiagTotal1 = (row1col4 + row2col3 + row3col2 + row4col1);
        System.out.println("rightDiagTotal1" + rightDiagTotal1);
        winCondition(rightDiagTotal1);
        
        String rightDiagTotal2 = (row1col5 + row2col4 + row3col3 + row4col2 + row5col1);
        System.out.println("rightDiagTotal2" + rightDiagTotal2);
        winCondition(rightDiagTotal2);
        
        String rightDiagTotal3 = (row1col6 + row2col5 + row3col4 + row4col3 + row5col2 + row6col1);
        System.out.println("rightDiagTotal3" + rightDiagTotal3);
        winCondition(rightDiagTotal3);

        String rightDiagTotal4 = (row1col7 + row2col6 + row3col5 + row4col4 + row5col3 + row6col2 + row7col1);
        System.out.println("rightDiagTotal4" + rightDiagTotal4);
        winCondition(rightDiagTotal4);

        String rightDiagTotal5 = (row1col8 + row2col7 + row3col6 + row4col5 + row5col4 + row6col3 + row7col2 + row8col1);
        System.out.println("rightDiagTotal5" + rightDiagTotal5);
        winCondition(rightDiagTotal5);

        String rightDiagTotal6 = (row2col8 + row3col7 + row4col6 + row5col5 + row6col4 + row7col3 + row8col2);
        System.out.println("rightDiagTotal6" + rightDiagTotal6);
        winCondition(rightDiagTotal6);

        String rightDiagTotal7 = (row3col8 + row4col7 + row5col6 + row6col5 + row7col4 + row8col3);
        System.out.println("rightDiagTotal7" + rightDiagTotal7);
        winCondition(rightDiagTotal7);
        
        String rightDiagTotal8 = (row4col8 + row5col7 + row6col6 + row7col5 + row8col4);
        System.out.println("rightDiagTotal8" + rightDiagTotal8);
        winCondition(rightDiagTotal8);       
    
        String rightDiagTotal9 = (row5col8 + row6col7 + row7col6 + row8col5);
        System.out.println("rightDiagTotal9" + rightDiagTotal9);
        winCondition(rightDiagTotal9);       

    }
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment1Frame().setVisible(true);
            }
        });
    }
    
    boolean xTurn;
    boolean x2Turn;
    JButton cross[][];
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
