

import java.awt.*;
import static java.awt.AWTEventMulticaster.add;
import java.awt.event.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Test2 extends javax.swing.JFrame implements ActionListner {
    private static boolean Palyer1Sybol;

    /**
     * Creates new form Test2
     */
    public Test2() {
        initComponents();
        //String Palyer1Sybol []; // get this from players
        //String Palyer2Sybol []; // get this from players
        //String Palyer3Sybol []; // get this from players
        //String Player1Name[]; //Name of Player-1
        //String Player2Name[]; //Name of Player-2
        //String Player3Name[]; //Name of Player-3
        JButton grid[][] = null;
       
        
        //xTurn = true;  // whose turn it is
        
        //grid = new JButton[8][8]; // array to hold button objects
        
        grid[0][0] = jButton3;
        grid[0][1] = jButton4;
        grid[0][2] = jButton5;
        grid[0][3] = jButton5;
        grid[0][4] = jButton7;
        grid[0][5] = jButton8;
        grid[0][6] = jButton8;
        grid[0][7] = jButton10;
      
        grid[1][0] = jButton11;
        grid[1][1] = jButton12;
        grid[1][2] = jButton13;
        grid[1][3] = jButton14;
        grid[1][4] = jButton15;
        grid[1][5] = jButton16;
        grid[1][6] = jButton17;
        grid[1][7] = jButton18;
        
        grid[2][0] = jButton19;
        grid[2][1] = jButton20;
        grid[2][2] = jButton21;
        grid[2][3] = jButton22;
        grid[2][4] = jButton23;
        grid[2][5] = jButton24;
        grid[2][6] = jButton25;
        grid[2][7] = jButton26;
        
        grid[3][0] = jButton27;
        grid[3][1] = jButton28;
        grid[3][2] = jButton29;
        grid[3][3] = jButton30;
        grid[3][4] = jButton31;
        grid[3][5] = jButton32;
        grid[3][6] = jButton33;
        grid[3][7] = jButton34;
        
        grid[4][0] = jButton35;
        grid[4][1] = jButton36;
        grid[4][2] = jButton37;
        grid[4][3] = jButton38;
        grid[4][4] = jButton39;
        grid[4][5] = jButton40;
        grid[4][6] = jButton41;
        grid[4][7] = jButton42;
        
        grid[5][0] = jButton43;
        grid[5][1] = jButton44;
        grid[5][2] = jButton45;
        grid[5][3] = jButton46;
        grid[5][4] = jButton47;
        grid[5][5] = jButton48;
        grid[5][6] = jButton49;
        grid[5][7] = jButton50;
        
        grid[6][0] = jButton51;
        grid[6][1] = jButton52;
        grid[6][2] = jButton53;
        grid[6][3] = jButton54;
        grid[6][4] = jButton55;
        grid[6][5] = jButton56;
        grid[6][6] = jButton57;
        grid[6][7] = jButton58;
        
        grid[7][0] = jButton59;
        grid[7][1] = jButton60;
        grid[7][2] = jButton61;
        grid[7][3] = jButton62;
        grid[7][4] = jButton63;
        grid[7][5] = jButton64;
        grid[7][6] = jButton65;
        grid[7][7] = jButton66;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe_For 3 Players");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void selectButton(JButton button) {
       /* if (button.getText().equals("")) {
            if (xTurn) {
                button.setText("X");
            } else {
                button.setText("O");
            }

            xTurn = !xTurn;
        }

        checkForTheWin(); */
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test2().setVisible(true);
            }
        });
        System.out.println(Palyer1Sybol);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables

    private void SetLocationRelative(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void SetSize(int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
}
